### ISSUE TITLE
anaconda-command broken: AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by WouterVH** [Anaconda-Server/docs.anaconda.org#182]
Just giving this tutorial a small testdrive
http://docs.anaconda.org/#BuildingPackagesWithAnacondaCloud

```
 > wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
 > chmod u+x Miniconda2-latest-Linux-x86_64.sh

 > ./Miniconda2-latest-Linux-x86_64.sh -b -f -p .  
 > cd $HOME/miniconda2
 > bin/conda install anaconda-client anaconda-build conda-build
```

my root-env:
```
>  bin/conda list     
# packages in environment at /data2/opt/data/projects/miniconda:
#
anaconda-build            0.13.1                   py27_0    defaults
anaconda-client           1.1.2                    py27_0    defaults
clyent                    1.0.0                    py27_0    defaults
conda                     3.18.3                   py27_0    defaults
conda-build               1.18.1                   py27_0    defaults
conda-env                 2.4.4                    py27_0    defaults
freetype                  2.5.5                         0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            0    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         0    defaults
markupsafe                0.23                     py27_0    defaults
openssl                   1.0.2d                        0    defaults
patchelf                  0.6                           0    defaults
pillow                    3.0.0                    py27_1    defaults
pip                       7.1.2                    py27_0    defaults
psutil                    3.2.2                    py27_0    defaults
pycosat                   0.6.1                    py27_0    defaults
pycrypto                  2.6.1                    py27_0    defaults
python                    2.7.10                        2    defaults
python-dateutil           2.4.2                    py27_0    defaults
pytz                      2015.7                   py27_0    defaults
pyyaml                    3.11                     py27_1    defaults
readline                  6.2                           2    defaults
requests                  2.8.1                    py27_0    defaults
setuptools                18.4                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.8.4.1                       1    defaults
tk                        8.5.18                        0    defaults
wheel                     0.26.0                   py27_1    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         0    defaults
```

but anaconda is broken:
```
>  bin/anaconda --help
    Traceback (most recent call last):
    File "bin/anaconda", line 6, in <module>
        sys.exit(main())
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 82, in main
        description=__doc__, version=version)
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 50, in binstar_main
        add_subparser_modules(parser, sub_command_module, 'conda_server.subcommand')
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/clyent/__init__.py", line 132, in add_subparser_modules
        add_parser(subparsers)
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/binstar_build_client/scripts/worker.py", line 37, in add_parser
        add_subparser_modules(parser, worker_commands, 'conda_server_build.subcommand')
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/clyent/__init__.py", line 127, in add_subparser_modules
        command_module.add_parser(subparsers)
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/binstar_build_client/worker_commands/docker_run.py", line 43, in add_parser
        description, __doc__)
    File "/data2/opt/data/projects/miniconda/lib/python2.7/site-packages/binstar_build_client/worker_commands/run.py", line 65, in add_parser
        'conda-bld', '{platform}'),
    File "/data2/opt/data/projects/miniconda/lib/python2.7/posixpath.py", line 70, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'

```

**Comment by srossross** [comment]
Hi @WouterVH, It looks like this bug is coming from here: https://github.com/Anaconda-Server/anaconda-build/blob/develop/binstar_build_client/utils/__init__.py#L7

We will work on finding a permanent solution, but for now:

 1. Can you make sure the `conda` command is in your `PATH` variable?
 2. OR uninstall anaconda-build

**Comment by WouterVH** [comment]
IMHO  activating a virtualenv using "source bin/activate" should be a usability-enhancement, but code should not break if the env is not activated this way.

In this situation, if we don't find conda in the current $PATH,  it should look in the directory where the anaconda-executable is located.   
Actually I would introspect this directory first and then search in the $PATH

Snippet below works for me:

```
import os
import sys

CONDA_EXE = 'conda.exe' if os.name == 'nt' else 'conda'

def get_conda_root_prefix():
    for entry in os.environ.get('PATH').split(os.pathsep):

        if os.path.isdir(entry) and CONDA_EXE in os.listdir(entry):
            conda_exe_path = os.path.realpath(os.path.join(entry, 'conda'))
            bin_dir = os.path.dirname(conda_exe_path)
            return os.path.dirname(bin_dir)

    # conda not found in $PATH, try directory where current executable is located
    canonical_dir_current_executable = os.path.dirname(os.path.realpath(sys.argv[0]))
    if CONDA_EXE in os.path.dirname(canonical_dir_current_executable):
        return os.path.dirname(canonical_dir_current_executable)
```

**Comment by WouterVH** [comment]
when using symlinks, you can even first try without resolving the symlink.

**Comment by srossross** [comment]
Thanks

**Comment by WouterVH** [comment]
my snippet above contains errors (double dirname).

improved:
```
def get_conda_root_prefix():
    canonical_dir_current_executable = os.path.dirname(os.path.realpath(sys.argv[0]))
    paths = [canonical_dir_current_executable, ] + os.environ.get('PATH').split(os.pathsep)
    
    for entry in paths:
        if os.path.isdir(entry) and CONDA_EXE in os.listdir(entry):
            conda_exe_path = os.path.realpath(os.path.join(entry, 'conda'))
            bin_dir = os.path.dirname(conda_exe_path)
            return os.path.dirname(bin_dir)

```

**Comment by srossross** [comment]
Thanks @WouterVH a fix is in the pipeline.
