### ISSUE TITLE
Binstar authentication/login

### ISSUE THREAD

**Issue by Casolt** [Anaconda-Server/docs.anaconda.org#47]
I was following "Submit your first build" under "Binstar Build". I had already done the first two commands, and this is from the third command.
```
C:\Users\Home\conda_build_test>binstar package --create Calvinly/conda_build_tes
t
Using binstar api site https://api.binstar.org
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: Y
[Unauthorized] Invalid Token

C:\Users\Home\conda_build_test>binstar login
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: Y
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: Y
[Unauthorized] Invalid Token

C:\Users\Home\conda_build_test>binstar logout
Using binstar api site https://api.binstar.org
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: n
[BinstarError] The authentication token with name "binstar_client:Home@Home-THIN
K" already exists

C:\Users\Home\conda_build_test>conda update binstar
Fetching package metadata: ..Could not connect to http://localhost:8080/win-64/
.Warning: you may need to login to binstar again with 'binstar login' to access
private packages(https://conda.binstar.org/t/<TOKEN>/calvinly/win-64/, 401 Clien
t Error: UNAUTHORIZED)..
Solving package specifications: .
Package plan for installation in environment C:\Users\Home\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    binstar-0.9.2              |           py27_1         114 KB
    clyent-0.3.2               |           py27_0          13 KB
    ------------------------------------------------------------
                                           Total:         127 KB

The following packages will be UPDATED:

    binstar: 0.9.1-py27_0 --> 0.9.2-py27_1
    clyent:  0.3.1-py27_0 --> 0.3.2-py27_0

Proceed ([y]/n)? y

Fetching packages ...
binstar-0.9.2- 100% |###############################| Time: 0:00:00 467.01 kB/s
clyent-0.3.2-p 100% |###############################| Time: 0:00:00 211.36 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%

C:\Users\Home\conda_build_test>binstar login
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: Y
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: n
[BinstarError] The authentication token with name "binstar_client:Home@Home-THIN
K" already exists

C:\Users\Home\conda_build_test>binstar show config
Using binstar api site https://api.binstar.org
[NotFound] User config does not exist

C:\Users\Home\conda_build_test>binstar show -config
usage: binstar-script.py show [-h] spec
binstar-script.py show: error: too few arguments

C:\Users\Home\conda_build_test>binstar --version
binstar-script.py Command line client (version 0.8)

C:\Users\Home\conda_build_test>binstar package --create Calvinly/conda_build_tes
t
Using binstar api site https://api.binstar.org
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: Calvinly
Calvinly's Password:
[error] It appears you are already logged in from host Home-THINK
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--h
ostname"
Would you like to continue [Y|n]: Y
[Unauthorized] Invalid Token

C:\Users\Home\conda_build_test>
```

**Comment by riseriyo** [comment]
I am getting the same or similar error trying to log into Binstar using Windows XP. I removed the tokens, and tried again as well... but no go... I checked my Binstar account and it does not state any "Last Accessed" date in that column. 

Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Owner\My Documents\workspace>binstar login
Using binstar api site https://api.binstar.org
Username: riseriyo
riseriyo's Password:
[error] It appears you are already logged in from host tecnai-simulator-rise
[error] Logging in again will remove the previous token.
[error] Otherwise you can login again and specify a different hostname with "--hostname"
Would you like to continue [Y|n]: Y
riseriyo's [WindowsError] 5
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\binstar-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 94, in main
    description=__doc__, version=version)
  File "C:\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 76, in binstar_
main
    return args.main(args)
  File "C:\Miniconda\lib\site-packages\binstar_client\commands\login.py", line 92, in main
    interactive_login(args)
  File "C:\Miniconda\lib\site-packages\binstar_client\commands\login.py", line 88, in inter
active_login
    store_token(token, args)
  File "C:\Miniconda\lib\site-packages\binstar_client\utils\__init__.py", line 166, in stor
e_token
    os.unlink(tokenfile)
WindowsError: [Error 5] Access is denied: u'C:\\Documents and Settings\\Owner\\Local Settin
gs\\Application Data\\ContinuumIO\\binstar\\https%3A%2F%2Fapi.binstar.org.token'

C:\Documents and Settings\Owner\My Documents\workspace>

**Comment by srossross** [comment]
@riseriyo the issue seems to be that binstar can not remove the file `u'C:\\Documents and Settings\\Owner\\Local Settin
gs\\Application Data\\ContinuumIO\\binstar\\https%3A%2F%2Fapi.binstar.org.token'` 
do you know why this would be?

**Comment by srossross** [comment]
Can you try removing it manually?

**Comment by riseriyo** [comment]
Hi, srossross, 

No. I don't know why it is not removing it manually. Could it be because it is being used in a virtual machine on a Mac? IDK. 

Do you mean remove it from my Binstar account via web or via command? I tried the former but don't know how to do the latter at command line.

**Comment by riseriyo** [comment]
Just a quick update. I think the issue involved the C:\Documents and Settings\Owner\Local Settings\ directory and its files and subdirectories were hidden. I removed the 'hidden' attribute from the directory and its files and subdirectories and was able to log in successfully at the command prompt in Windows XP. But I tried it a couple of times (logging in/out) at the command prompt, and there is still some inconsistent results. But at least I got this far...

**Comment by drf5n** [comment]
I get similar problems:

     $ binstar upload /Users/drf/anaconda/conda-bld/osx-64/pyproj-1.9.4-py27_0.tar.bz2
    Using binstar api site https://api.binstar.org
    The action you are performing requires authentication, please sign in:
    Using binstar api site https://api.binstar.org
    Username: drf5n
    drf5n's Password: 
    [error] It appears you are already logged in from host v21837.local 
    [error] Logging in again will remove the previous token. 
    [error] Otherwise you can login again and specify a different hostname with "--hostname" 
    Would you like to continue [Y|n]: y
    drf5n's login successful
    Using binstar api site https://api.binstar.org
    [Unauthorized] This domain requires token authentication

Before this, I was trying to add pyproj a relatively fresh install of anaconda with this result:

    $ conda install -c https://conda.binstar.org/jjhelmus pyproj
    Fetching package metadata: ....Error: HTTPError: 401 Client Error: UNAUTHORIZED: http://conda.binstar.org/jjhelmus/noarch/

When binstar offers to continue and remove a token, is it removed from something local or remote?

How does one invoke with the --hostname?  It isn't apparent from 'binstar upload --help' or 'binstar --help'?

I have a Mac 10.10.3 Yosemite with anaconda and some of my versions are:

    $ binstar -V
    binstar Command line client (version 0.10.1)
    $ conda --version
    conda 3.13.0

**Comment by stephenakearns** [comment]
Hi @electronwill - I see you closed this earlier in the fall - I'm tracking it down - do you happen to recall why it was closed? (I see we transferred the issue into another repo to track it there, and the other is still open -  the comments indicate the issue persists.) Thoughts?

**Comment by electronwill** [comment]
The procedure I was following, which I'm now worried may not have been the right one, was to move all issues not relating to docs over to the other repo, link them to the issue here with the explanation, and close the issue here. Closing the issue here wasn't meant to indicate that the problem had been solved, just that it would be tracked in the other repo instead of the docs repo.

**Comment by stephenakearns** [comment]
Hi @electronwill - I think that's the process I had originally proposed, but realize that it's not respecting the open-source nature of this repo so going forward, we'll leave them open until deployed in production and resolved.

**Comment by stephenakearns** [comment]
@Casolt we've made a number of updates to the client. This issue may have been resolved by those issues. Are you able to update your client to the latest version (v1.2.1) and re-test. If you encounter an issue, please let us know and we'll continue to investigate further. To update: 

`conda update anaconda-client`

**Comment by connie** [comment]
I'm getting the same error, using both Windows 7 Enterprise 32-bit and 64-bit.  Strangely, it hasn't occurred on my other Windows machines (nor on Linux), but these are new VM's.  

    anaconda upload wget-1.16.3-0.tar.bz2 -u RMG
    detecting package type ...
    conda
    extracting package attributes for upload ...
    done
    Using Anaconda Cloud api site https://api.anaconda.org
    [ERROR]
    Traceback (most recent call last):
      File "C:\Users\Connie\Anaconda\Scripts\anaconda-script.py", line 5, in <module>
        sys.exit(main())
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 87, in main
        description=__doc__, version=version)
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 66, in binstar_main
        return args.main(args)
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\commands\upload.py", line 186, in main
        add_release(aserver_api, args, username, package_name, version, release_attrs)
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\commands\upload.py", line 124, in add_release
        create_release(aserver_api, username, package_name, version, release_attrs['description'])
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\commands\upload.py", line 37, in create_release
        announce, description)
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\__init__.py", line 324, in add_release
        self._check_response(res)
      File "C:\Users\Connie\Anaconda\lib\site-packages\binstar_client\__init__.py", line 161, in _check_response
        raise ErrCls(msg, res.status_code)
    Unauthorized: (u'This domain requires token authentication', 401) 

Using the command `anaconda login` also freezes, as well as the token generation step `TOKEN=$(anaconda auth --create --name MyToken)`.  

    $ binstar -V
    binstar-script.py Command line client (version 1.2.1)
    $ conda --version
    conda 3.19.0

**Comment by connie** [comment]
Update: The upload function works fine using command prompt, just not git bash.  Another problem with git bash is that typing `python` in the terminal also freezes and doesn't pop up the usual Anaconda Python in the command line.
