### ISSUE TITLE
404 release version does not exist and 500 Internal server error

### ISSUE THREAD

**Issue by gmarkall** [Anaconda-Server/docs.anaconda.org#49]
Attempting to binstar upload a numba package with the numbot account results in the following traceback:

```
Using binstar api site https://api.binstar.org
[BinstarError] Internal server error 
Traceback (most recent call last):
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/commands/upload.py", line 119, in add_release
    binstar.release(username, package_name, version)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/__init__.py", line 284, in release
    self._check_response(res)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/__init__.py", line 154, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("release version=u'0.16a1' does not exist", 404)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/commands/upload.py", line 187, in main
    add_release(binstar, args, username, package_name, version, release_attrs)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/commands/upload.py", line 124, in add_release
    create_release(binstar, username, package_name, version, release_attrs['description'])
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/commands/upload.py", line 38, in create_release
    announce, description)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/__init__.py", line 317, in add_release
    self._check_response(res)
  File "/home/jenkins/anaconda/envs/jenkins_numba_binstar_3.3/lib/python3.3/site-packages/binstar_client/__init__.py", line 154, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Internal server error', 500)
```

(This occurred some number of minutes after Nov 18, 2014 9:46:43 AM, in case that is helpful).

The package that is being uploaded is built with this recipe: https://github.com/gmarkall/numba/tree/binstar/buildscripts/condarecipe.binstar

Any help/thoughts/advice appreciated.

**Comment by electronwill** [comment]
Has this been resolved?
