### ISSUE TITLE
binstar auth -l fails with a Traceback

### ISSUE THREAD

**Issue by ovz** [Anaconda-Server/docs.anaconda.org#53]
I created a token for an organization and was able to see it in the portal at https://binstar.org/organization/salford_systems/settings/access

Name	Last Accessed	Expires		
internal_test_access	--	01/17/16 (11 months from now)	details 	view 

BTW I noticed that 

* Clicking internal_test_access leads to binstar.org home page.
* details and view lead to the same display
* Details display doesn't show the actual token, only token ID, which is different. 

I wanted to see if I have to keep track of my tokens myself. So I tried to list tokens via command file and received the following. 
```
$ binstar auth -l
Using binstar api site https://api.binstar.org
The action you are performing requires authentication, please sign in:
Using binstar api site https://api.binstar.org
Username: ovz
ovz's Password:
[WindowsError] 5
Traceback (most recent call last):
  File "c:\Anaconda\x64\Scripts\binstar-script.py", line 9, in <module>
    load_entry_point('binstar==0.9.5', 'console_scripts', 'binstar')()
  File "C:\Anaconda\x64\lib\site-packages\binstar_client\scripts\cli.py", line 9
4, in main
    description=__doc__, version=version)
  File "C:\Anaconda\x64\lib\site-packages\binstar_client\scripts\cli.py", line 8
0, in binstar_main
    interactive_login(args)
  File "C:\Anaconda\x64\lib\site-packages\binstar_client\commands\login.py", lin
e 88, in interactive_login
    store_token(token, args)
  File "C:\Anaconda\x64\lib\site-packages\binstar_client\utils\__init__.py", lin
e 166, in store_token
    os.unlink(tokenfile)
WindowsError: [Error 5] Access is denied: u'C:\\Users\\BuildMaster\\AppData\\Loc
al\\ContinuumIO\\binstar\\https%3A%2F%2Fapi.binstar.org.token'
```

**Comment by electronwill** [comment]
Apologies for the slow response! Was this resolved?

**Comment by ovz** [comment]
Looks like it was
